### ISSUE TITLE
design paremeter added to story but not showing 

### ISSUE THREAD

**Issue by A7DC** [pocka/storybook-addon-designs#43]
Hi there, apologies for the second issue/question!

I've added the `withDesign` and have added the `design` parameter as per the docs but the addon doesn't appear in my Storybook UI:

`stories/1-Button.stories.js`:

```
import { withDesign } from "storybook-addon-designs";
import Button from "../src/components/Button";

export default {
  title: "My Stories",
  decorators: [withDesign],
};

export const myStory = () => ({
  components: { Button },
  template: "<Button label='hello'/>",
});

myStory.story = {
  name: "My awesome story",
  parameters: {
    design: {
      type: "figma",
      url: "https://www.figma.com/file/LKQ4FJ4bTnCSjedbRpk931/Sample-File",
    },
  },
};
```

`src/components/Button.vue`:

```

<template>
  <button>{{ label }}</button>
</template>

<script>
export default {
  name: "Button",
  props: {
    label: String
  }
};
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
button {
  background: red;
}
</style>
```

`.storybook/main.js`:

```
module.exports = {
  stories: ['../stories/**/*.stories.js'],
  addons: ['storybook-addon-designs']
};

```

Any ideas what I'm doing wrong here?

The code can be seen [here](https://github.com/A7DC/storybookvueaddonstest) if that helps

Edit: If I look in the console I can see that the story is wrapped in the Figma component, so not sure why it doesn't display?

**Comment by pocka** [comment]
If you're using `storybook-addon-designs@5.2.0` or below, probably you need to specify `storybook-addon-designs/register` to `main.js`

```js
// .storybook/main.js
module.exports = {
  // ...
  addons: ['storybook-addon-designs/register']
}
```

Current master is at `v5.3.0-alpha` (I know it's confusing though, sorry :scream:).

**Comment by A7DC** [comment]
Hi Pocka,

Thanks for your help! 

So I tried two things (neither of them worked sadly). 

**First thing**

I changed this bit of my `package.json`: 

`"storybook-addon-designs": "5.3.0-alpha.1",`

and then ran `npm i` again.

`.storybook/main.js` looked like:

```
module.exports = {
  stories: ['../stories/**/*.stories.js'],
  addons: ['storybook-addon-designs']
};
```

This didn't work. And so

**Second thing**

I changed this bit of my `package.json`: 

`"storybook-addon-designs": "^5.2.0",`

and then ran `npm i` again.

`.storybook/main.js` looked like:

```
module.exports = {
  stories: ['../stories/**/*.stories.js'],
  addons: ['storybook-addon-designs/register']
};
```

**Comment by pocka** [comment]
@A7DC 

- Does a `Design` tab in an addons panel exist? (if not, the problem is at an addon registration process `register.js`)
- Any browser console or terminal output log lines related to the addon?

**Comment by A7DC** [comment]
Hey Pocka,

No design tab exists currently! :(

My browser returns the following:

```

printWarning @ vendors~main.f6bf0f75e4901d6720de.bundle.js:114022
error @ vendors~main.f6bf0f75e4901d6720de.bundle.js:113994
warnAboutRenderPhaseUpdatesInDEV @ vendors~main.f6bf0f75e4901d6720de.bundle.js:137184
scheduleUpdateOnFiber @ vendors~main.f6bf0f75e4901d6720de.bundle.js:135099
enqueueSetState @ vendors~main.f6bf0f75e4901d6720de.bundle.js:126573
push../node_modules/react/cjs/react.development.js.Component.setState @ vendors~main.f6bf0f75e4901d6720de.bundle.js:153782
setState @ vendors~main.f6bf0f75e4901d6720de.bundle.js:5986
newState @ vendors~main.f6bf0f75e4901d6720de.bundle.js:8738
_callee$ @ vendors~main.f6bf0f75e4901d6720de.bundle.js:8737
tryCatch @ vendors~main.f6bf0f75e4901d6720de.bundle.js:169446
invoke @ vendors~main.f6bf0f75e4901d6720de.bundle.js:169675
prototype.<computed> @ vendors~main.f6bf0f75e4901d6720de.bundle.js:169498
asyncGeneratorStep @ vendors~main.f6bf0f75e4901d6720de.bundle.js:8635
_next @ vendors~main.f6bf0f75e4901d6720de.bundle.js:8637
(anonymous) @ vendors~main.f6bf0f75e4901d6720de.bundle.js:8637
(anonymous) @ vendors~main.f6bf0f75e4901d6720de.bundle.js:8637
setState @ vendors~main.f6bf0f75e4901d6720de.bundle.js:8769
setAddonState @ vendors~main.f6bf0f75e4901d6720de.bundle.js:6760
useAddonState @ vendors~main.f6bf0f75e4901d6720de.bundle.js:6208
(anonymous) @ vendors~main.f6bf0f75e4901d6720de.bundle.js:4476
renderWithHooks @ vendors~main.f6bf0f75e4901d6720de.bundle.js:128737
mountIndeterminateComponent @ vendors~main.f6bf0f75e4901d6720de.bundle.js:131416
beginWork @ vendors~main.f6bf0f75e4901d6720de.bundle.js:132530
beginWork$1 @ vendors~main.f6bf0f75e4901d6720de.bundle.js:137113
performUnitOfWork @ vendors~main.f6bf0f75e4901d6720de.bundle.js:136088
workLoopSync @ vendors~main.f6bf0f75e4901d6720de.bundle.js:136064
performSyncWorkOnRoot @ vendors~main.f6bf0f75e4901d6720de.bundle.js:135690
(anonymous) @ vendors~main.f6bf0f75e4901d6720de.bundle.js:125023
unstable_runWithPriority @ vendors~main.f6bf0f75e4901d6720de.bundle.js:172240
runWithPriority$1 @ vendors~main.f6bf0f75e4901d6720de.bundle.js:124973
flushSyncCallbackQueueImpl @ vendors~main.f6bf0f75e4901d6720de.bundle.js:125018
flushSyncCallbackQueue @ vendors~main.f6bf0f75e4901d6720de.bundle.js:125006
scheduleUpdateOnFiber @ vendors~main.f6bf0f75e4901d6720de.bundle.js:135133
enqueueSetState @ vendors~main.f6bf0f75e4901d6720de.bundle.js:126573
push../node_modules/react/cjs/react.development.js.Component.setState @ vendors~main.f6bf0f75e4901d6720de.bundle.js:153782
(anonymous) @ vendors~main.f6bf0f75e4901d6720de.bundle.js:150288
(anonymous) @ vendors~main.f6bf0f75e4901d6720de.bundle.js:150328
exec @ vendors~main.f6bf0f75e4901d6720de.bundle.js:175511
wrapper @ vendors~main.f6bf0f75e4901d6720de.bundle.js:175538
addListener @ vendors~main.f6bf0f75e4901d6720de.bundle.js:40895
onElementDetectable @ vendors~main.f6bf0f75e4901d6720de.bundle.js:40970
ready @ vendors~main.f6bf0f75e4901d6720de.bundle.js:40659
process @ vendors~main.f6bf0f75e4901d6720de.bundle.js:31249
processBatch @ vendors~main.f6bf0f75e4901d6720de.bundle.js:31162
setTimeout (async)
raf @ vendors~main.f6bf0f75e4901d6720de.bundle.js:31207
requestFrame @ vendors~main.f6bf0f75e4901d6720de.bundle.js:31208
processBatchAsync @ vendors~main.f6bf0f75e4901d6720de.bundle.js:31189
addFunction @ vendors~main.f6bf0f75e4901d6720de.bundle.js:31149
install @ vendors~main.f6bf0f75e4901d6720de.bundle.js:40667
makeDetectable @ vendors~main.f6bf0f75e4901d6720de.bundle.js:40688
attachListenerToElement @ vendors~main.f6bf0f75e4901d6720de.bundle.js:40963
push../node_modules/element-resize-detector/src/collection-utils.js.utils.forEach @ vendors~main.f6bf0f75e4901d6720de.bundle.js:39783
listenTo @ vendors~main.f6bf0f75e4901d6720de.bundle.js:40931
handleDOMNode @ vendors~main.f6bf0f75e4901d6720de.bundle.js:150377
componentDidMount @ vendors~main.f6bf0f75e4901d6720de.bundle.js:150340
commitLifeCycles @ vendors~main.f6bf0f75e4901d6720de.bundle.js:133748
commitLayoutEffects @ vendors~main.f6bf0f75e4901d6720de.bundle.js:136737
callCallback @ vendors~main.f6bf0f75e4901d6720de.bundle.js:114122
invokeGuardedCallbackDev @ vendors~main.f6bf0f75e4901d6720de.bundle.js:114171
invokeGuardedCallback @ vendors~main.f6bf0f75e4901d6720de.bundle.js:114226
commitRootImpl @ vendors~main.f6bf0f75e4901d6720de.bundle.js:136475
unstable_runWithPriority @ vendors~main.f6bf0f75e4901d6720de.bundle.js:172240
runWithPriority$1 @ vendors~main.f6bf0f75e4901d6720de.bundle.js:124973
commitRoot @ vendors~main.f6bf0f75e4901d6720de.bundle.js:136315
finishSyncRender @ vendors~main.f6bf0f75e4901d6720de.bundle.js:135741
performSyncWorkOnRoot @ vendors~main.f6bf0f75e4901d6720de.bundle.js:135727
scheduleUpdateOnFiber @ vendors~main.f6bf0f75e4901d6720de.bundle.js:135122
updateContainer @ vendors~main.f6bf0f75e4901d6720de.bundle.js:138307
(anonymous) @ vendors~main.f6bf0f75e4901d6720de.bundle.js:138692
unbatchedUpdates @ vendors~main.f6bf0f75e4901d6720de.bundle.js:135837
legacyRenderSubtreeIntoContainer @ vendors~main.f6bf0f75e4901d6720de.bundle.js:138691
render @ vendors~main.f6bf0f75e4901d6720de.bundle.js:138774
renderStorybookUI @ vendors~main.f6bf0f75e4901d6720de.bundle.js:27491
(anonymous) @ vendors~main.f6bf0f75e4901d6720de.bundle.js:18760
Promise.then (async)
./node_modules/@storybook/core/dist/client/manager/index.js @ vendors~main.f6bf0f75e4901d6720de.bundle.js:18757
__webpack_require__ @ runtime~main.ab2010a73de94f6ff9b3.bundle.js:85
(anonymous) @ main.9f2fe4d413ad476adf64.bundle.js:10
__webpack_require__ @ runtime~main.ab2010a73de94f6ff9b3.bundle.js:85
checkDeferredModules @ runtime~main.ab2010a73de94f6ff9b3.bundle.js:46
webpackJsonpCallback @ runtime~main.ab2010a73de94f6ff9b3.bundle.js:33
(anonymous) @ main.9f2fe4d413ad476adf64.bundle.js:1
Show 14 more frames
vendors~main.f6bf0f75e4901d6720de.bundle.js:31155 [Violation] 'setTimeout' handler took 193ms
content-script.js:7  WebVREmu  Polyfill http://localhost:6006/iframe.html?id=my-stories--my-story&viewMode=story
2vendors~main.f6bf0f75e4901d6720de.bundle.js:10984 message arrived at manager storyRender
vue.esm.js:9088 You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html
index.js:19 message arrived at preview channelCreated
vendors~main.f6bf0f75e4901d6720de.bundle.js:10984 message arrived at manager setStories {stories: {…}}
vendors~main.f6bf0f75e4901d6720de.bundle.js:10984 message arrived at manager STORYBOOK_ADDON_DESIGNS/update_config {type: "figma", url: "https://www.figma.com/file/LKQ4FJ4bTnCSjedbRpk931/Sample-File"}
vendors~main.f6bf0f75e4901d6720de.bundle.js:10984 message arrived at manager storyRendered my-stories--my-story
vendors~main.f6bf0f75e4901d6720de.bundle.js:10984 message arrived at manager storyUnchanged {id: "my-stories--my-story", revision: 0, kind: "My Stories", name: "My awesome story", viewMode: "story"}
vendors~main.f6bf0f75e4901d6720de.bundle.js:10984 message arrived at manager storiesConfigured
```

I've pushed up the latest [here](https://github.com/A7DC/storybookvueaddonstest)

**Comment by pocka** [comment]
```
viewer.js.br:16 viewer build: sk
```

This line comes from Figma's Live Embed Kit, so certainly the addon (Figma iframe) exists on your Storybook UI.

Did you check `Show addons` is on?

![pocka github io_storybook-addon-designs_](https://user-images.githubusercontent.com/13316015/79540069-7b5e2680-80c2-11ea-83cc-a8c61745e05d.png)

**Comment by A7DC** [comment]
Hey Pocka,

Yeah that `Show addons` is also checked :S

**Comment by pocka** [comment]
@A7DC I cloned your repo then run Storybook, and it worked.

![dev pocka io_6006__path=_story_my-stories--my-story (1)](https://user-images.githubusercontent.com/13316015/79637612-e8091c00-81bb-11ea-80aa-7ede54e2e831.png)

I think there is something related to browser cache or Storybook UI bug. Would you try opening a Storybook in an incognito tab or other browsers? If it does not solve the problem, a screenshot will be helpful.

**Comment by A7DC** [comment]
It was a caching issue - thanks Pocka!! 👊
